[tool.poetry]
name = "internet-of-timesheets"
version = "0.1.0"
description = ""
authors = ["Matt McCarthy"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
